import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

interface ExportPDFOptions {
  elementId: string;
  filename: string;
  title: string;
  subtitle?: string;
}

export const exportToPDF = async ({ elementId, filename, title, subtitle }: ExportPDFOptions): Promise<void> => {
  const element = document.getElementById(elementId);
  if (!element) {
    throw new Error(`Element with id ${elementId} not found`);
  }

  // Hide elements that shouldn't be in the PDF (e.g., action buttons)
  const hideElements = document.querySelectorAll('.no-print');
  hideElements.forEach(el => (el as HTMLElement).style.display = 'none');

  try {
    // A4 dimensions in mm
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = pdf.internal.pageSize.getHeight();
    const margin = 15;
    
    // Header
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(22);
    pdf.setTextColor(40, 40, 40);
    pdf.text("InsightIQ Business Report", margin, 20);
    
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(14);
    pdf.setTextColor(100, 100, 100);
    pdf.text(`Dataset: ${title}`, margin, 28);
    
    if (subtitle) {
      pdf.setFontSize(10);
      pdf.text(subtitle, margin, 34);
    }
    
    // Horizontal Line
    pdf.setDrawColor(200, 200, 200);
    pdf.line(margin, 38, pdfWidth - margin, 38);

    // Capture the DOM element
    // scale: 2 improves image quality
    const canvas = await html2canvas(element, { 
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: '#ffffff'
    });
    
    const imgData = canvas.toDataURL('image/png');
    
    // Calculate image dimensions to fit on A4
    const contentWidth = pdfWidth - (margin * 2);
    const contentHeight = (canvas.height * contentWidth) / canvas.width;
    
    // Start drawing image below the header (y=45)
    let yPos = 45;
    
    // Check if it fits on one page, otherwise we would need pagination
    // For simplicity in MVP, we just scale it to fit or let it run off
    // However, if it's too tall, let's scale it down to fit one page for now
    let finalHeight = contentHeight;
    let finalWidth = contentWidth;
    
    const maxAllowedHeight = pdfHeight - yPos - margin;
    
    if (contentHeight > maxAllowedHeight) {
      // Scale down to fit the height
      finalHeight = maxAllowedHeight;
      finalWidth = (canvas.width * finalHeight) / canvas.height;
    }
    
    // Center it horizontally if scaled down by height
    const xPos = margin + (contentWidth - finalWidth) / 2;

    pdf.addImage(imgData, 'PNG', xPos, yPos, finalWidth, finalHeight);
    
    // Footer
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    const dateStr = new Date().toLocaleString();
    pdf.text(`Generated by InsightIQ on ${dateStr}`, margin, pdfHeight - 10);
    pdf.text(`Page 1 of 1`, pdfWidth - margin - 20, pdfHeight - 10);

    // Save
    pdf.save(`${filename}.pdf`);
    
  } finally {
    // Restore hidden elements
    hideElements.forEach(el => (el as HTMLElement).style.display = '');
  }
};
